# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mainWIndow.ui'
#
# Created by: PyQt5 UI code generator 5.13.2
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(892, 712)
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(Dialog)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.label_4 = QtWidgets.QLabel(Dialog)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.verticalLayout_5.addWidget(self.label_4)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.label_2 = QtWidgets.QLabel(Dialog)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.verticalLayout_2.addWidget(self.label_2)
        self.plain_buffer = QtWidgets.QPlainTextEdit(Dialog)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.plain_buffer.setFont(font)
        self.plain_buffer.setObjectName("plain_buffer")
        self.verticalLayout_2.addWidget(self.plain_buffer)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.button_to_redis = QtWidgets.QPushButton(Dialog)
        self.button_to_redis.setObjectName("button_to_redis")
        self.horizontalLayout.addWidget(self.button_to_redis)
        self.button_to_postgre = QtWidgets.QPushButton(Dialog)
        self.button_to_postgre.setObjectName("button_to_postgre")
        self.horizontalLayout.addWidget(self.button_to_postgre)
        self.verticalLayout_2.addLayout(self.horizontalLayout)
        self.horizontalLayout_2.addLayout(self.verticalLayout_2)
        self.verticalLayout_4 = QtWidgets.QVBoxLayout()
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.label = QtWidgets.QLabel(Dialog)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.verticalLayout.addWidget(self.label)
        self.plain_redis = QtWidgets.QPlainTextEdit(Dialog)
        self.plain_redis.setEnabled(True)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.plain_redis.setFont(font)
        self.plain_redis.setObjectName("plain_redis")
        self.verticalLayout.addWidget(self.plain_redis)
        self.button_redis = QtWidgets.QPushButton(Dialog)
        self.button_redis.setObjectName("button_redis")
        self.verticalLayout.addWidget(self.button_redis)
        self.verticalLayout_4.addLayout(self.verticalLayout)
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.label_3 = QtWidgets.QLabel(Dialog)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.verticalLayout_3.addWidget(self.label_3)
        self.plain_postgre = QtWidgets.QPlainTextEdit(Dialog)
        self.plain_postgre.setEnabled(True)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.plain_postgre.setFont(font)
        self.plain_postgre.setObjectName("plain_postgre")
        self.verticalLayout_3.addWidget(self.plain_postgre)
        self.button_postgre = QtWidgets.QPushButton(Dialog)
        self.button_postgre.setObjectName("button_postgre")
        self.verticalLayout_3.addWidget(self.button_postgre)
        self.verticalLayout_4.addLayout(self.verticalLayout_3)
        self.horizontalLayout_2.addLayout(self.verticalLayout_4)
        self.verticalLayout_5.addLayout(self.horizontalLayout_2)

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.label_4.setText(_translate("Dialog", "ПиРБД, ПР 5, Килюп Л.А."))
        self.label_2.setText(_translate("Dialog", "БУФЕР"))
        self.button_to_redis.setText(_translate("Dialog", "В REDIS"))
        self.button_to_postgre.setText(_translate("Dialog", "В POSTGRE SQL"))
        self.label.setText(_translate("Dialog", "REDIS"))
        self.button_redis.setText(_translate("Dialog", "В БУФЕР"))
        self.label_3.setText(_translate("Dialog", "POSTGRE SQL"))
        self.button_postgre.setText(_translate("Dialog", "В БУФЕР"))
